name: CKBuild

shared:
  environment:
    variables:
      FLUTTER_VERSION: "3.32.0"

targets:
  - name: Runner
    platform: iOS

    scripts:
      - name: Set up Flutter and CocoaPods
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

    build:
      config: Release
