files:
  - source: /lib/l10n/app_en.arb
    translation: /lib/l10n/app_%two_letters_code%.arb
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        en-US: en_US
        en-GB: en_GB
        es-ES: es
        fr: fr
        pt-PT: pt
        sv-SE: sv
        zh-CN: zh
