files:
  - source: /expo/src/i18n/arb/app_en.arb
    translation: /expo/src/i18n/arb/app_%two_letters_code%.arb
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        en-US: en_US
        en-GB: en_GB
        es-ES: es
        pt-PT: pt
        sv-SE: sv
        zh-CN: zh
