/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 0821b131774f35a4f4e36ebd566869d2)
interface __BaseEnv_Env {
	EMAIL_DOMAIN: "e2e-mail.clashk.ing";
	OTP_TTL_SECONDS: "600";
	MAX_EMAIL_BYTES: "262144";
	OTP_API_TOKEN: string;
	OTP_INBOX: DurableObjectNamespace<import("./src/index").OtpInbox>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "OtpInbox";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EMAIL_DOMAIN" | "OTP_TTL_SECONDS" | "MAX_EMAIL_BYTES" | "OTP_API_TOKEN">> {}
}
