name: Deploy to Closed Test

on:
  push:
    branches:
      - play-store

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'  # Specify your Flutter version

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > android/local.properties
          echo "flutter.sdk=$HOME/flutter" >> android/local.properties
          echo "flutter.buildMode=debug" >> android/local.properties
          echo "flutter.versionName=1.0.0" >> android/local.properties
          echo "flutter.versionCode=7" >> android/local.properties
          echo "flutter.minSdkVersion=21" >> android/local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build
        run: ./gradlew build
        working-directory: android

      - name: Assemble Release Bundle
        run: ./gradlew bundleRelease
        working-directory: android

      - name: Sign Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE_FILE }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Tag Release
        run: |
          version_name=$(date +'%Y%m%d%H%M%S')
          echo "Tagging release with tag $version_name"
          git tag $version_name
          git push origin --tags

      - name: Create service_account.json
        run: echo '${{ secrets.GOOGLE_PLAY_JSON_KEY }}' > service_account.json

      - name: Deploy to Closed Test
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: service_account.json
          packageName: ${{ secrets.PACKAGE_NAME }}
          releaseFile: android/app/build/outputs/bundle/release/app-release.aab
          track: closed
          status: inProgress
          inAppUpdatePriority: 3
          whatsNewDirectory: update-news