name: Execute Script on Merge to Main

on:
  push:
    branches:
      - l10n_main 

jobs:
  run-script:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2 

    - name: Execute Localization Script
      run: |
        cd lib/l10n/
        sed -i '2s/"@@locale": "es-ES"/"@@locale": "es"/' app_es.arb
        sed -i '2s/"@@locale": "zh-CN"/"@@locale": "zh"/' app_zh.arb
        sed -i '2s/"@@locale": "pt-PT"/"@@locale": "pt"/' app_pt.arb
        sed -i '2s/"@@locale": "sv-SE"/"@@locale": "sv"/' app_sv.arb
