name: Test Secret Formats

on:
  push:
    branches:
      - chore/backend
  workflow_dispatch:  # Allows manual trigger

jobs:
  test-secrets:
    name: Detect Secret Formats
    runs-on: ubuntu-latest
    
    steps:
      - name: Test iOS Secrets Format
        env:
          IOS_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_BASE64 }}
          IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          IOS_PROVISIONING_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
        run: |
          echo "🔍 Testing iOS Secret Formats..."
          echo "========================================"
          
          # Test IOS_CERTIFICATE_BASE64
          if [ -n "$IOS_CERTIFICATE_BASE64" ]; then
            echo "📱 IOS_CERTIFICATE_BASE64:"
            echo "  Length: ${#IOS_CERTIFICATE_BASE64} characters"
            
            # Test if it can be base64 decoded
            if echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > /tmp/test_p12.p12 2>/dev/null; then
              echo "  ✅ Format: Valid BASE64 (can be decoded)"
              file_info=$(file /tmp/test_p12.p12 2>/dev/null || echo "unknown")
              echo "  📄 Content type: $file_info"
              rm -f /tmp/test_p12.p12
            else
              echo "  ❌ Format: RAW content (base64 decode failed)"
            fi
            echo "  First 50 chars: ${IOS_CERTIFICATE_BASE64:0:50}..."
          else
            echo "📱 IOS_CERTIFICATE_BASE64: ❌ NOT SET"
          fi
          echo ""
          
          # Test IOS_CERTIFICATE_PASSWORD
          if [ -n "$IOS_CERTIFICATE_PASSWORD" ]; then
            echo "🔐 IOS_CERTIFICATE_PASSWORD:"
            echo "  ✅ SET (length: ${#IOS_CERTIFICATE_PASSWORD} characters)"
          else
            echo "🔐 IOS_CERTIFICATE_PASSWORD: ❌ NOT SET"
          fi
          echo ""
          
          # Test IOS_PROVISIONING_PROFILE_BASE64
          if [ -n "$IOS_PROVISIONING_PROFILE_BASE64" ]; then
            echo "📄 IOS_PROVISIONING_PROFILE_BASE64:"
            echo "  Length: ${#IOS_PROVISIONING_PROFILE_BASE64} characters"
            
            # Check length first (should be 10,000+ chars for real profile)
            if [ ${#IOS_PROVISIONING_PROFILE_BASE64} -lt 1000 ]; then
              echo "  ⚠️  WARNING: Length seems too short for a real provisioning profile"
            fi
            
            # Test if it can be base64 decoded
            if echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > /tmp/test_profile.mobileprovision 2>/dev/null; then
              echo "  ✅ Format: Valid BASE64 (can be decoded)"
              file_info=$(file /tmp/test_profile.mobileprovision 2>/dev/null || echo "unknown")
              echo "  📄 Content type: $file_info"
              
              # Check if it's a valid plist
              if command -v plutil >/dev/null 2>&1; then
                if plutil -lint /tmp/test_profile.mobileprovision >/dev/null 2>&1; then
                  echo "  ✅ Valid plist structure"
                else
                  echo "  ❌ Invalid plist structure"
                fi
              fi
              rm -f /tmp/test_profile.mobileprovision
            else
              echo "  ❌ Format: RAW content (base64 decode failed)"
            fi
            echo "  First 50 chars: ${IOS_PROVISIONING_PROFILE_BASE64:0:50}..."
          else
            echo "📄 IOS_PROVISIONING_PROFILE_BASE64: ❌ NOT SET"
          fi
          echo ""
          
          # Test App Store Connect API Key
          if [ -n "$APP_STORE_CONNECT_API_KEY" ]; then
            echo "🔑 APP_STORE_CONNECT_API_KEY:"
            echo "  Length: ${#APP_STORE_CONNECT_API_KEY} characters"
            if [[ "$APP_STORE_CONNECT_API_KEY" =~ ^-----BEGIN.* ]]; then
              echo "  ✅ Format: PEM format (.p8 content)"
            else
              echo "  ❓ Format: Unknown (should be .p8 file content)"
            fi
            echo "  First 50 chars: ${APP_STORE_CONNECT_API_KEY:0:50}..."
          else
            echo "🔑 APP_STORE_CONNECT_API_KEY: ❌ NOT SET"
          fi
          echo ""
          
          # Test API Key ID
          if [ -n "$APP_STORE_CONNECT_API_KEY_ID" ]; then
            echo "🆔 APP_STORE_CONNECT_API_KEY_ID:"
            echo "  ✅ SET: $APP_STORE_CONNECT_API_KEY_ID"
          else
            echo "🆔 APP_STORE_CONNECT_API_KEY_ID: ❌ NOT SET"
          fi
          echo ""
          
          # Test Issuer ID
          if [ -n "$APP_STORE_CONNECT_API_ISSUER_ID" ]; then
            echo "🏢 APP_STORE_CONNECT_API_ISSUER_ID:"
            echo "  ✅ SET: $APP_STORE_CONNECT_API_ISSUER_ID"
          else
            echo "🏢 APP_STORE_CONNECT_API_ISSUER_ID: ❌ NOT SET"
          fi
          echo ""
          
          echo "========================================"
          echo "🎯 SUMMARY:"
          echo "========================================"
          
          # Provide recommendations based on actual decode tests
          echo "🔧 WORKFLOW COMPATIBILITY:"
          
          if [ -n "$IOS_CERTIFICATE_BASE64" ]; then
            if echo "$IOS_CERTIFICATE_BASE64" | base64 --decode > /tmp/test_p12_final.p12 2>/dev/null; then
              echo "✅ IOS_CERTIFICATE_BASE64: Workflow will decode as base64"
              rm -f /tmp/test_p12_final.p12
            else
              echo "✅ IOS_CERTIFICATE_BASE64: Workflow will use as raw content"
            fi
          fi
          
          if [ -n "$IOS_PROVISIONING_PROFILE_BASE64" ]; then
            if echo "$IOS_PROVISIONING_PROFILE_BASE64" | base64 --decode > /tmp/test_profile_final.mobileprovision 2>/dev/null; then
              echo "✅ IOS_PROVISIONING_PROFILE_BASE64: Workflow will decode as base64"
              rm -f /tmp/test_profile_final.mobileprovision
            else
              echo "✅ IOS_PROVISIONING_PROFILE_BASE64: Workflow will use as raw content"
            fi
            
            # Special warning for short profiles
            if [ ${#IOS_PROVISIONING_PROFILE_BASE64} -lt 1000 ]; then
              echo "⚠️  IOS_PROVISIONING_PROFILE_BASE64: May be corrupted or incomplete!"
              echo "   Normal profiles are 10,000+ characters. Consider re-uploading."
            fi
          fi
          
          # Check if we have everything needed
          missing_secrets=()
          [ -z "$IOS_CERTIFICATE_BASE64" ] && missing_secrets+=("IOS_CERTIFICATE_BASE64")
          [ -z "$IOS_CERTIFICATE_PASSWORD" ] && missing_secrets+=("IOS_CERTIFICATE_PASSWORD")
          [ -z "$IOS_PROVISIONING_PROFILE_BASE64" ] && missing_secrets+=("IOS_PROVISIONING_PROFILE_BASE64")
          [ -z "$APP_STORE_CONNECT_API_KEY" ] && missing_secrets+=("APP_STORE_CONNECT_API_KEY")
          [ -z "$APP_STORE_CONNECT_API_KEY_ID" ] && missing_secrets+=("APP_STORE_CONNECT_API_KEY_ID")
          [ -z "$APP_STORE_CONNECT_API_ISSUER_ID" ] && missing_secrets+=("APP_STORE_CONNECT_API_ISSUER_ID")
          
          if [ ${#missing_secrets[@]} -eq 0 ]; then
            echo "🎉 All required secrets are set! TestFlight workflow should work."
          else
            echo "❌ Missing secrets: ${missing_secrets[*]}"
            echo "   Add these in GitHub → Settings → Secrets and variables → Actions"
          fi